import { defineConfig } from "@playwright/test"

// Baseline Playwright config, auto-generated by gboard. Override
// PLAYWRIGHT_BASE_URL in env to point tests at a deployed URL.
export default defineConfig({
  testDir: "./tests/e2e",
  testMatch: ["*.spec.ts"],
  use: { baseURL: process.env.PLAYWRIGHT_BASE_URL ?? "http://localhost:3000" },
  retries: 1,
  reporter: [["list"]],
})
