import { test, expect } from "@playwright/test"

// Baseline smoke test, auto-generated by gboard for greenfield boards.
// Edit me — this is just a starter so the pipeline has something to run.
test("home page loads without crashing", async ({ page }) => {
  await page.goto(process.env.PLAYWRIGHT_BASE_URL ?? "http://localhost:3000")
  await expect(page).not.toHaveTitle(/error/i)
  const body = await page.textContent("body")
  expect(body && body.length > 10).toBeTruthy()
})
